# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to "The Blog"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Founder of Voux, lead front-end engineer at Mozio Inc. JavaScript, Angular, React, conference speaker. Developer Expert at Google.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alexmac__
github_username:  alex-mac

# Build settings
markdown: kramdown